### ISSUE TITLE
Regenerate go.mod and go.sum

### ISSUE THREAD

**Issue by syphyr** [bitmold/OrbotIPtProxy#4]
https://github.com/bitmold/OrbotIPtProxy/blob/daf733bea7e6bcf6e291503e61d5337785b40f17/build-orbot.sh#L21

At this point in the script, new module dependencies are introduced for tun2sock and need to be added to go.mod and go.sum in IPtProxy.go. I suppose the best way to do this is execute "go mod" 
in the build script after adding new module dependencies.

**Comment by bitmold** [comment]
I suppose so, when you run `gomobile bind` it does find the dependencies anyway
```
go: finding module for package github.com/eycorsican/go-tun2socks/common/dns
go: finding module for package github.com/eycorsican/go-tun2socks/proxy/socks
go: finding module for package github.com/eycorsican/go-tun2socks/core
go: downloading github.com/eycorsican/go-tun2socks v1.16.11
go: found github.com/eycorsican/go-tun2socks/common/dns in github.com/eycorsican/go-tun2socks v1.16.11
go: found github.com/eycorsican/go-tun2socks/core in github.com/eycorsican/go-tun2socks v1.16.11
go: found github.com/eycorsican/go-tun2socks/proxy/socks in github.com/eycorsican/go-tun2socks v1.16.11
```

It's not a priority of mine to get this proper right now, especially since we're just embedding this library into an Android app and it's not a go application proper. I had issues building after running `go mod tidy` which is how I would normally add these missing deps. 

Open to a pull request if you get it figured out ...

**Comment by syphyr** [comment]
Yes, "go mod tidy" removes things that are needed and does not work correctly. I did not realize how "gomobile bind" worked when I opened this issue.  It works as it is, so you are right.  I'll close this as a non issue.
